resource_types:
- name: pull-request
  type: registry-image
  check_every: 5m
  source:
    repository: docker.io/tasruntime/github-pr-instances-resource

- name: gitto
  type: registry-image
  check_every: 5m
  source:
    repository: quay.io/konifay/concourse-git-resource
    tag: latest

resources:
- name: git-clone-resource
  type: gitto
  check_every: 5m
  webhook_token: ((ci-tron-webhook-token))
  source:
    branch: master
    uri: git@github.com:drahnr/ci-tron.git
    private_key: ((sirmergealot-ssh-key))
    paths: [ ".concourse/*" ]


- name: that-git-branch
  type: gitto
  check_every: 5m
  webhook_token: ((ci-tron-webhook-token))
  source:
    branch: master
    uri: git@github.com:drahnr/ci-tron.git
    private_key: ((sirmergealot-ssh-key))


- name: git-pull-request-resource
  type: pull-request
  webhook_token: ((ci-tron-webhook-token))
  check_every: 1m
  source:
    repository: drahnr/ci-tron
    access_token: ((sirmergealot-github-token))

jobs:
- name: update-how-pr-pipelines-are-updates
  plan:
  - get: git-master
    resource: git-clone-resource
    trigger: true
  - set_pipeline: self
    file: git-master/.concourse/root.yml

- name: update-pr-pipelines
  plan:
  - get: gitto
    resource: git-pull-request-resource
    trigger: true
    params:
      BRANCH: ((.:pr.branch))

  # load the pull request list
  - load_var: prlist
    file: pull-request/prs.json
  - across:
    - var: pr
      values: ((.:prlist))

    do:
      # fetch the pull request branch
      # it's not a very clean approach, but it avoids needing
      # another pipeline level indirection
      - task: pr-content
        public: false
        timeout: 10m
        params:
          GIT_PRIVATE_KEY: ((sirmergealot-ssh-key))
          GIT_BRANCH: ((.:pr.branch))
        image: env-glibc
        config:
          platform: linux
          outputs:
          - name: foo
          run:
            dir: foo
            path: sh
            args:
            - -exc
            - |
              mkdir -v -p ~/.ssh
              chmod -Rvf 0750 ~/.ssh
              echo "${GIT_PRIVATE_KEY}" > ~/.ssh/sirmergealot 
              git clone --branch ${GIT_BRANCH} git@github.com:drahnr/ci-tron.git foo

      - set_pipeline: that-pr
        file: foo/.concourse/pipelines/pr.yml
        instance_vars: {number: ((.:pr.number))}
