resource_types:
- name: pull-request
  type: registry-image
  check_every: 5m
  source:
    repository: docker.io/tasruntime/github-pr-instances-resource

resources:
- name: git-clone-resource
  type: git
  check_every: 5m
  webhook_token: ((ci-tron-webhook-token))
  source:
    branch: master
    uri: git@github.com:drahnr/ci-tron.git
    private_key: ((sirmergealot-ssh-key))
    paths: [ ".concourse/*" ]


- name: git-pull-request-resource
  type: pull-request
  webhook_token: ((ci-tron-webhook-token))
  check_every: 1m
  source:
    repository: drahnr/ci-tron
    access_token: ((sirmergealot-github-token))

jobs:
- name: update-how-pr-pipelines-are-updates
  plan:
  - get: git-master
    resource: git-clone-resource
    trigger: true
  - set_pipeline: self
    file: git-master/.concourse/root.yml

- name: update-pr-pipelines
  plan:
  # load the pull request list
  - get: pull-request
    resource: git-pull-request-resource
    trigger: true
  - load_var: prlist
    file: pull-request/prs.json
  
  # across all prs in the list...
  - across:
    - var: pr
      values: ((.:prlist))

    do:
      # fetch the pull request branch
      # it's not a very clean approach, but it avoids needing
      # another pipeline level indirection
      - task: pr-content
        timeout: 10m
        params:
          GIT_PRIVATE_KEY: ((sirmergealot-ssh-key))
          GIT_BRANCH: ((.:pr.branch))
        image: env-glibc
        config:
          public: false
          platform: linux
          outputs:
          - name: foo
          run:
            dir: foo
            path: sh
            args:
            - -exc
            - |
              mkdir -v -p ~/.ssh
              chmod -Rvf 0750 ~/.ssh
              echo "${GIT_PRIVATE_KEY}" > ~/.ssh/sirmergealot 
              git clone --branch ${GIT_BRANCH} git@github.com:drahnr/ci-tron.git foo

      - set_pipeline: ci-tron-prs
        file: foo/.concourse/pipelines/pr.yml
        instance_vars: {number: ((.:pr.number))}
